#pragma kernel CSMain

RWTexture2D<float4> Result;

Texture2D<float4> Texture;

int2 RenderOrigin;
int2 RenderSize;

float2 TextureSize;

SamplerState LinearMirrorSampler;

[numthreads(32,32,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	int2 newID = int2(id.x + RenderOrigin.x, id.y + RenderOrigin.y);

	float2 uv = float2(newID / TextureSize);

	Result[newID] = Texture.SampleLevel(LinearMirrorSampler, uv, 0);
}
