#pragma kernel CSMain

RWTexture2D<float4> Result;

Texture2D<float4> Texture;

float2 CropOrigin;
float2 TextureSize;

SamplerState LinearMirrorSampler;

[numthreads(32, 32, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
	if (id.x > TextureSize.x || id.y > TextureSize.y)
		return;

	float2 uv = (id.xy + CropOrigin) / TextureSize;
	Result[id.xy] = Texture.SampleLevel(LinearMirrorSampler, uv, 0);
}
